// 競合分析用モックデータ

export interface CompetitorAd {
  id: string;
  advertiser: string;
  adTitle: string;
  platforms: string[];
  startDate: string;
  daysRunning: number;
  variations: number;
  // バズスコア内訳
  scaleScore: number;     // 配信規模（30点満点）
  freshnessScore: number; // 鮮度（20点満点）
  buzzScore: number;      // 話題性（25点満点）
  creativeScore: number;  // クリエイティブ力（25点満点）
  totalScore: number;     // 合計（100点満点）
  // AI分析
  creativeAnalysis: string;
  appealTriggers: string[];
  suggestion: string;
  // 詳細データ
  scaleDetail: { period: string; platformCount: number; variationCount: number };
  freshnessDetail: { startDate: string; daysAgo: number; recency: string };
  buzzDetail: { snsMentions: number; searchTrend: string; trendScore: string };
  creativeDetail: { format: string; copyStrength: string; visualImpact: string; ctaClarity: string };
  // 実際の広告への導線
  adLibraryUrl?: string;
  websiteUrl?: string;
}

export const mockCompetitors: CompetitorAd[] = [
  {
    id: 'comp_1',
    advertiser: '北海道スイーツ工房',
    adTitle: '【期間限定】北海道産クリームチーズケーキ',
    platforms: ['Facebook', 'Instagram'],
    startDate: '2026-02-15',
    daysRunning: 51,
    variations: 8,
    scaleScore: 26,
    freshnessScore: 12,
    buzzScore: 22,
    creativeScore: 23,
    totalScore: 83,
    creativeAnalysis: '季節感のある暖色系のビジュアルに「期間限定」の緊急性訴求を組み合わせた高効率クリエイティブ。食欲を刺激するシズル感のある商品画像が特徴。',
    appealTriggers: ['期間限定（緊急性）', 'シズル感（食欲訴求）', '産地訴求（信頼性）', 'ギフト訴求（用途提案）'],
    suggestion: '同様の季節限定訴求+産地訴求の組み合わせをテスト。「北海道産」のような産地ブランドの活用を検討。',
    scaleDetail: { period: '51日間配信中', platformCount: 2, variationCount: 8 },
    freshnessDetail: { startDate: '2026-02-15', daysAgo: 51, recency: '配信開始から約2ヶ月' },
    buzzDetail: { snsMentions: 340, searchTrend: '上昇トレンド', trendScore: '高' },
    creativeDetail: { format: '画像+カルーセル', copyStrength: '高（数字・限定感あり）', visualImpact: '高（シズル系）', ctaClarity: '明確（購入ボタン）' },
  },
  {
    id: 'comp_2',
    advertiser: '和菓子の老舗 京花堂',
    adTitle: '母の日ギフト特集 - 上品な和スイーツ',
    platforms: ['Facebook', 'Instagram', 'Messenger'],
    startDate: '2026-03-20',
    daysRunning: 18,
    variations: 12,
    scaleScore: 28,
    freshnessScore: 18,
    buzzScore: 20,
    creativeScore: 21,
    totalScore: 87,
    creativeAnalysis: '母の日に向けたギフト訴求で、高級感のあるパッケージ写真と「感謝を届ける」という感情訴求が効果的。ターゲットを45-65歳女性に絞り込んでいる可能性が高い。',
    appealTriggers: ['イベント訴求（母の日）', '感情訴求（感謝）', '高級感（パッケージ）', '送料無料（障壁除去）'],
    suggestion: '母の日向けギフトセットの広告を急いで準備。「感謝」「贈り物」などの感情キーワードを活用。',
    scaleDetail: { period: '18日間配信中', platformCount: 3, variationCount: 12 },
    freshnessDetail: { startDate: '2026-03-20', daysAgo: 18, recency: '直近2週間以内に開始' },
    buzzDetail: { snsMentions: 180, searchTrend: '急上昇', trendScore: '高' },
    creativeDetail: { format: '動画+カルーセル', copyStrength: '高（感情+イベント）', visualImpact: '高（高級感）', ctaClarity: '明確（ギフト購入）' },
  },
  {
    id: 'comp_3',
    advertiser: '九州フルーツファーム',
    adTitle: '朝採れいちご直送便 - 完熟あまおう',
    platforms: ['Instagram'],
    startDate: '2026-03-01',
    daysRunning: 37,
    variations: 5,
    scaleScore: 18,
    freshnessScore: 14,
    buzzScore: 18,
    creativeScore: 22,
    totalScore: 72,
    creativeAnalysis: '「朝採れ」「直送」という鮮度訴求が強いクリエイティブ。Instagram中心の配信でビジュアル重視。Reels動画で収穫シーンを見せるストーリーテリング型。',
    appealTriggers: ['鮮度訴求（朝採れ）', 'ストーリーテリング（収穫シーン）', '限定感（数量限定）', '産地直送（信頼性）'],
    suggestion: '自社商品でも生産過程を見せるReels動画を検討。「作り手の想い」ストーリーは共感を生みやすい。',
    scaleDetail: { period: '37日間配信中', platformCount: 1, variationCount: 5 },
    freshnessDetail: { startDate: '2026-03-01', daysAgo: 37, recency: '配信開始から約1ヶ月' },
    buzzDetail: { snsMentions: 95, searchTrend: '横ばい', trendScore: '中' },
    creativeDetail: { format: 'Reels動画', copyStrength: '中（鮮度訴求中心）', visualImpact: '高（収穫シーン）', ctaClarity: '明確（注文ボタン）' },
  },
  {
    id: 'comp_4',
    advertiser: '洋菓子マルシェ BONBON',
    adTitle: 'チョコレート定期便 - 毎月届く幸せ',
    platforms: ['Facebook'],
    startDate: '2025-12-10',
    daysRunning: 118,
    variations: 15,
    scaleScore: 24,
    freshnessScore: 6,
    buzzScore: 15,
    creativeScore: 19,
    totalScore: 64,
    creativeAnalysis: '定期便・サブスクモデルの訴求。長期配信（118日）から効果が安定していると推測。クリエイティブバリエーションが多く、継続的なABテストを実施している。',
    appealTriggers: ['サブスク訴求（定期便）', '手軽さ（毎月届く）', '初回割引（障壁除去）', 'レビュー活用（社会的証明）'],
    suggestion: '自社でも定期便オプションがあれば広告訴求を検討。長期配信の安定パターンは参考になる。',
    scaleDetail: { period: '118日間配信中', platformCount: 1, variationCount: 15 },
    freshnessDetail: { startDate: '2025-12-10', daysAgo: 118, recency: '配信開始から約4ヶ月（安定期）' },
    buzzDetail: { snsMentions: 45, searchTrend: '横ばい', trendScore: '低' },
    creativeDetail: { format: '画像+動画', copyStrength: '中（定期便メリット中心）', visualImpact: '中', ctaClarity: '明確（定期購入）' },
  },
  {
    id: 'comp_5',
    advertiser: '東北お取り寄せ本舗',
    adTitle: '【ギネス認定】世界一の〇〇',
    platforms: ['Facebook', 'Instagram'],
    startDate: '2026-03-25',
    daysRunning: 13,
    variations: 4,
    scaleScore: 16,
    freshnessScore: 20,
    buzzScore: 23,
    creativeScore: 20,
    totalScore: 79,
    creativeAnalysis: '「ギネス認定」という強力な社会的証明を活用したクリエイティブ。直近開始で急速にリーチを拡大中。話題性の高い権威訴求が効果的。',
    appealTriggers: ['権威訴求（ギネス認定）', '好奇心（世界一）', '社会的証明', '新商品感（直近配信）'],
    suggestion: '自社でも受賞歴・認定があれば広告コピーに活用。第三者評価は説得力が高い。',
    scaleDetail: { period: '13日間配信中', platformCount: 2, variationCount: 4 },
    freshnessDetail: { startDate: '2026-03-25', daysAgo: 13, recency: '直近2週間以内に開始' },
    buzzDetail: { snsMentions: 520, searchTrend: '急上昇', trendScore: '高' },
    creativeDetail: { format: '画像', copyStrength: '高（権威+好奇心）', visualImpact: '中', ctaClarity: '明確' },
  },
  {
    id: 'comp_6',
    advertiser: '信州ナチュラルファーム',
    adTitle: '無添加ジャム詰め合わせ - 朝食を彩る',
    platforms: ['Facebook', 'Instagram'],
    startDate: '2026-02-01',
    daysRunning: 66,
    variations: 6,
    scaleScore: 22,
    freshnessScore: 10,
    buzzScore: 16,
    creativeScore: 20,
    totalScore: 68,
    creativeAnalysis: '「無添加」「自然派」という健康訴求と、朝食シーンのライフスタイル提案を組み合わせたクリエイティブ。ターゲットは健康意識の高い30-50代女性と推測。',
    appealTriggers: ['健康訴求（無添加）', 'ライフスタイル提案', 'セット販売（まとめ買い）', '口コミ活用'],
    suggestion: '健康・自然派訴求は共感を得やすい。自社商品でも素材のこだわりを前面に出すクリエイティブをテスト。',
    scaleDetail: { period: '66日間配信中', platformCount: 2, variationCount: 6 },
    freshnessDetail: { startDate: '2026-02-01', daysAgo: 66, recency: '配信開始から約2ヶ月' },
    buzzDetail: { snsMentions: 75, searchTrend: '横ばい', trendScore: '中' },
    creativeDetail: { format: '画像+カルーセル', copyStrength: '中（健康訴求）', visualImpact: '高（食卓シーン）', ctaClarity: '明確（購入）' },
  },
  {
    id: 'comp_7',
    advertiser: '瀬戸内レモンファクトリー',
    adTitle: '完熟レモンケーキ - SNSで話題沸騰',
    platforms: ['Instagram'],
    startDate: '2026-03-28',
    daysRunning: 11,
    variations: 3,
    scaleScore: 14,
    freshnessScore: 19,
    buzzScore: 24,
    creativeScore: 22,
    totalScore: 79,
    creativeAnalysis: 'SNSでの話題性を訴求に活用した「バンドワゴン効果」型のクリエイティブ。UGC（ユーザー生成コンテンツ）風の写真が自然で信頼感が高い。',
    appealTriggers: ['社会的証明（SNSで話題）', 'UGC風ビジュアル', '限定感（完熟）', 'フォトジェニック訴求'],
    suggestion: 'UGC風クリエイティブは広告感を薄め、CTRが高くなる傾向。お客様の写真を活用した広告をテストすべき。',
    scaleDetail: { period: '11日間配信中', platformCount: 1, variationCount: 3 },
    freshnessDetail: { startDate: '2026-03-28', daysAgo: 11, recency: '直近2週間以内に開始' },
    buzzDetail: { snsMentions: 890, searchTrend: '急上昇', trendScore: '高' },
    creativeDetail: { format: 'Reels+画像', copyStrength: '高（話題性+限定）', visualImpact: '高（UGC風）', ctaClarity: '明確' },
  },
  {
    id: 'comp_8',
    advertiser: '京都茶寮 抹茶庵',
    adTitle: '老舗の抹茶スイーツ定期便',
    platforms: ['Facebook'],
    startDate: '2026-01-15',
    daysRunning: 83,
    variations: 10,
    scaleScore: 20,
    freshnessScore: 5,
    buzzScore: 12,
    creativeScore: 18,
    totalScore: 55,
    creativeAnalysis: '老舗ブランドの信頼性とサブスクモデルを組み合わせた安定配信型。長期間の配信（83日）から、一定のROASを維持していると推測。',
    appealTriggers: ['ブランド訴求（老舗）', 'サブスク（定期便）', '和の高級感', '初回特典'],
    suggestion: '長期安定配信のパターンは参考になる。サブスクモデルの導入可能性を検討。',
    scaleDetail: { period: '83日間配信中', platformCount: 1, variationCount: 10 },
    freshnessDetail: { startDate: '2026-01-15', daysAgo: 83, recency: '配信開始から約3ヶ月' },
    buzzDetail: { snsMentions: 30, searchTrend: '横ばい', trendScore: '低' },
    creativeDetail: { format: '画像', copyStrength: '中（ブランド訴求）', visualImpact: '中', ctaClarity: '明確（定期購入）' },
  },
  {
    id: 'comp_9',
    advertiser: '沖縄マンゴーパラダイス',
    adTitle: '今年も解禁！完熟マンゴー予約受付中',
    platforms: ['Facebook', 'Instagram', 'Messenger'],
    startDate: '2026-03-15',
    daysRunning: 24,
    variations: 7,
    scaleScore: 24,
    freshnessScore: 16,
    buzzScore: 21,
    creativeScore: 23,
    totalScore: 84,
    creativeAnalysis: '季節の旬と予約限定を組み合わせた「今しか買えない」訴求が強力。3プラットフォーム×7バリエーションの大規模展開で本気度が高い。',
    appealTriggers: ['季節限定（旬）', '予約限定（希少性）', '産地直送', '先行予約特典'],
    suggestion: '季節商品の「予約受付」訴求は緊急性と希少性を同時に演出できる。自社の季節商品でも活用すべき。',
    scaleDetail: { period: '24日間配信中', platformCount: 3, variationCount: 7 },
    freshnessDetail: { startDate: '2026-03-15', daysAgo: 24, recency: '約3週間前に開始' },
    buzzDetail: { snsMentions: 280, searchTrend: '上昇トレンド', trendScore: '高' },
    creativeDetail: { format: '動画+カルーセル', copyStrength: '高（限定+季節）', visualImpact: '高（シズル系）', ctaClarity: '明確（予約）' },
  },
  {
    id: 'comp_10',
    advertiser: '新潟コシヒカリ直売所',
    adTitle: '令和7年産 新米予約 - 農家直送',
    platforms: ['Facebook'],
    startDate: '2026-03-10',
    daysRunning: 29,
    variations: 4,
    scaleScore: 16,
    freshnessScore: 15,
    buzzScore: 14,
    creativeScore: 17,
    totalScore: 62,
    creativeAnalysis: '農家直送の信頼性訴求と新米の季節感を組み合わせたシンプルなクリエイティブ。Facebook単体配信で中高年男性もターゲットに含めている。',
    appealTriggers: ['産地直送（信頼性）', '新米（季節感）', '農家の顔が見える', '送料無料'],
    suggestion: '生産者の顔が見える広告は信頼感が高い。自社でも生産者インタビューやストーリーを活用。',
    scaleDetail: { period: '29日間配信中', platformCount: 1, variationCount: 4 },
    freshnessDetail: { startDate: '2026-03-10', daysAgo: 29, recency: '約1ヶ月前に開始' },
    buzzDetail: { snsMentions: 55, searchTrend: '横ばい', trendScore: '低' },
    creativeDetail: { format: '画像', copyStrength: '中（産地+季節）', visualImpact: '中', ctaClarity: '明確（予約）' },
  },
];
